# Generated by Django 5.0.4 on 2024-04-05 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyValues',
            fields=[
                ('CurrValueId', models.IntegerField(primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
