# Generated by Django 5.0.4 on 2024-04-05 18:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('album_page', '0003_alter_albums_ownid'),
        ('colType_page', '0001_initial'),
        ('condition_page', '0001_initial'),
        ('country_page', '0001_initial'),
        ('currencyType_page', '0001_initial'),
        ('currencyValue_page', '0001_initial'),
        ('material_page', '0001_initial'),
        ('status_page', '0001_initial'),
        ('year_page', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Collectables',
            fields=[
                ('ColId', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('Name', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=200)),
                ('AlbLoc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='album_page.albums')),
                ('ColType', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='colType_page.coltypes')),
                ('Condition', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='condition_page.conditions')),
                ('Country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='country_page.countries')),
                ('CurrType', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='currencyType_page.currencytypes')),
                ('CurrValue', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='currencyValue_page.currencyvalues')),
                ('Material', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='material_page.materials')),
                ('Owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('Status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='status_page.statuses')),
                ('Year', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='year_page.years')),
            ],
        ),
    ]
