# Generated by Django 5.0.4 on 2024-04-19 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album_page', '0003_alter_albums_ownid'),
        ('collectables_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectables',
            name='AlbLoc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='album_page.albums'),
        ),
    ]
