# Generated by Django 5.0.4 on 2024-04-06 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('collectables_page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Photo', models.ImageField(upload_to='collectables_photos/')),
                ('ColId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collectables_page.collectables')),
            ],
        ),
    ]
