# Generated by Django 5.0.4 on 2024-04-05 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Albums',
            fields=[
                ('AlbLocId', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('Name', models.CharField(max_length=100)),
                ('Page', models.IntegerField()),
                ('PageRow', models.IntegerField()),
                ('PageCol', models.IntegerField()),
            ],
        ),
    ]
