# Generated by Django 5.0.4 on 2024-04-06 13:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('collectables_page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemPrices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('TransDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('ColId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collectables_page.collectables')),
            ],
        ),
    ]
